# docker-compose.yml
version: '3.8'
services:
  # main application
  web:
    container_name: eqa_automation_dashboard
    build:
          context: .
          dockerfile: Dockerfile
    image: eqa-dash:multi-stage-1.0
    ports:
      - "8000:8000"
